Special action log
xenown/GoSushi pull request #19
Opened 2020-08-30 04:37 UTC by RobNadal

2020-08-31 15:34 UTC, selinali2010 commented on gosushi_client/src/components/Board.jsx
> +          <span className="hovertext">You cannot undo this action</span>
Loool I fixed this in my PR too

2020-08-31 16:06 UTC, selinali2010 requested changes

2020-08-31 16:06 UTC, selinali2010 commented on gosushi_client/src/components/SpecActionsLog.jsx
> +            details = <span>, stealing a(n) <b className={cCardCN}>{entry.chosenCard}</b> from <b>{entry.stolenFromPlayer}</b>'s hand'.</span>
I think there's an extra apostrophe (') after the word "hand".
![image](https://user-images.githubusercontent.com/30204513/91738100-00337380-eb7e-11ea-9b5a-0c0605827be7.png)

2020-08-31 16:06 UTC, selinali2010 commented on gosushi_client/src/index.scss
> +  --soysaunce: #f49759;
"soysaunce" -> "soysauce"

2020-08-31 16:06 UTC, selinali2010 commented on gosushi_client/src/components/SpecActionsLog.scss
> +.log-soysaunce { color: var(--soysaunce); }
"soysaunce" -> "soysauce"

2020-09-01 00:08 UTC, hannahli2010 approved these changes

2020-09-01 01:50 UTC, selinali2010 approved these changes

2020-09-01 02:02 UTC, merged